[package]
name = "rustgg"
version = "0.2.1"
edition = "2021"
description = "自動でcommitをする\nUTCから時間を持ってきて[fix]UTCtimeを記述してコミットを行う"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.31", features = ["derive"] }
exec = "0.3.1"
