[package]
name = "rustgg"
version = "0.2.0"
edition = "2021"
description = "半自動化Commit\n現状はaddfileとcommitが動く？pushに関しては未検証"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.31", features = ["derive"] }
exec = "0.3.1"
